# Generated by Django 5.1.7 on 2025-04-16 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_artworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artwork',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
