# Generated by Django 5.0.2 on 2025-05-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_artwork_image_artwork_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(default='', upload_to='artworks/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ArtworkImage',
        ),
    ]
