# Generated by Django 5.0.2 on 2025-05-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_remove_artwork_is_approved_artwork_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
    ]
