# Generated by Django 5.0.2 on 2025-05-11 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_remove_artwork_likes'),
        ('marketplace', '0007_userprofile_facebook_userprofile_instagram_and_more'),
    ]

    operations = [
    ]
